### ISSUE TITLE
Error: Deprecated Packages and Missing Dependencies

### ISSUE THREAD

**Issue by RfadnjdExt** [Aruh1/stardust#12]
**Issue Description:**
I encountered several errors while running the project, including warnings about deprecated packages and missing dependencies. These errors are affecting the functionality of the project and preventing it from running correctly.

**Steps to Reproduce:**
1. Clone the project repository.
2. Install project dependencies using `npm install`.
3. Start the project using `npm start`.

**Expected Behavior:**
The project should be installed and started without any errors, allowing it to function properly.

**Actual Behavior:**
1. Deprecated package warnings:
   - `formidable@1.2.6`: Please upgrade to the latest version, formidable@v2 or formidable@v3. More details can be found at [https://bit.ly/2ZEqIau](https://bit.ly/2ZEqIau).
   - `superagent@6.1.0`: Please upgrade to v7.0.2+ of superagent. Numerous issues have been fixed in the newer version. Check the releases tab at [https://github.com/visionmedia/superagent/releases](https://github.com/visionmedia/superagent/releases) for more information.
   - `node-opus@0.3.3`: This project is unmaintained. Consider using @discordjs/opus as an alternative.

2. Compilation and installation error:
   - `libsodium`: Compilation of libsodium failed with an error related to the missing `libtool`.

3. Missing dependency error:
   - The project requires the `dotenv` module, but it cannot be found.

**Error Messages:**
```
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent. We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing. See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated node-opus@0.3.3: This project is unmaintained. See @discordjs/opus for an alternative.
npm ERR! code 1
npm ERR! path /home/container/node_modules/sodium
...
Error: Cannot find module 'dotenv'
...
```

**Environment:**
- Operating System: Linux [e.g., Windows 10, macOS Big Sur]
- Node.js Version: 18.16.1 [e.g., 18.16.1]
- NPM Version: [e.g., 7.24.0]

**Additional Information:**
- Any recent changes made to the project or its dependencies.
- The content of the `package.json` file if applicable.
- Any relevant code snippets or configuration files that may help identify the issue.
- Any other observations or insights that might be helpful for troubleshooting.

**Possible Solution:**
1. Update the deprecated packages:
   - Upgrade `formidable` to the latest version, `formidable@v2`, or `formidable@v3`.
   - Upgrade `superagent` to v7.0.2+.
   - Replace `node-opus` with `@discordjs/opus`.

2. Resolve the compilation error:
   - Ensure `libtool` is installed on the system.

3. Install missing dependency:
   - Run `npm install dotenv` to install the required `dotenv` module.

**Related Issues/PRs:**
- #10 

**Screenshots:**
![image](https://github.com/Aruh1/stardust/assets/40250666/0e05f451-ab69-4b53-9597-b2a80fb27dfc)

**Additional Context:**
package lama lebih meyakinkan

**Comment by Aruh1** [comment]
Fix with docker image Puppeteer and delete package sodium
